<?php

include_once "abstract.php";
include_once "interface.php";

class Meo extends dongvat implements keu,an,sinhsan {

    public function ahihi()
    {
        parent::ahihi(); // TODO: Change the autogenerated stub
    }

    public function keu_ntn()
    {
        // TODO: Implement keu_ntn() method.
        echo "meo meo meo";
    }
    public function thongtin()
    {
        // TODO: Implement thongtin() method.
        echo "day la con meo";
    }

    public function tenloai()
    {
        // TODO: Implement tenloai() method.
        echo "meo nha";
    }

    public function an_ntn()
    {
        // TODO: Implement an_ntn() method.
        echo "uong sua + an com";
    }

    public function sinh_ntn()
    {
        // TODO: Implement sinh_ntn() method.
        echo "de";
    }
}

$a = new Meo();
echo "<br>";
$a->keu_ntn();
echo "<br>";
$a->ahihi();
echo "<br>";
$a->an_ntn();
echo "<br>";
$a->sinh_ntn();
echo "<br>";
$a->tenloai();
echo "<br>";
$a->thongtin();
